plugins {
    id("serialization-convention")
    id("ioc-convention")
    alias(libs.plugins.ktlint)
    id("jacoco")
}

group = "lib"

// Bakes the release version (gradle.properties VERSION_NAME, bumped by
// release-please) into a compile-time constant: a generated source survives
// GraalVM native-image compilation without resource registration.
// The commit SHA comes from the environment (GIT_COMMIT_SHA overrides the
// GITHUB_SHA that GitHub Actions always sets) — null on local builds.
val generateBuildInfo by tasks.registering {
    val versionName = providers.gradleProperty("VERSION_NAME")
    val commitSha =
        providers
            .environmentVariable("GIT_COMMIT_SHA")
            .orElse(providers.environmentVariable("GITHUB_SHA"))
            .orElse("")
    inputs.property("versionName", versionName)
    inputs.property("commitSha", commitSha)
    val outputDir = layout.buildDirectory.dir("generated/buildInfo/kotlin")
    outputs.dir(outputDir)
    doLast {
        val commit = commitSha.get().takeIf { it.isNotBlank() }?.take(7)
        val commitLiteral = commit?.let { "\"$it\"" } ?: "null"
        val file = outputDir.get().file("instanceconfig/BuildInfo.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            "// Generated by the generateBuildInfo Gradle task — do not edit.\n" +
                "package instanceconfig\n" +
                "\n" +
                "/** Build-time metadata baked in by Gradle. */\n" +
                "object BuildInfo {\n" +
                "    const val VERSION: String = \"" + versionName.get() + "\"\n" +
                "\n" +
                "    /** Short SHA of the built commit; null when unknown (local build). */\n" +
                "    val COMMIT: String? = " + commitLiteral + "\n" +
                "}\n",
        )
    }
}

kotlin {
    sourceSets.named("main") {
        kotlin.srcDir(generateBuildInfo)
    }
}
