import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Firebase project configuration (ADR-005 push).
///
/// **These are placeholder values** so the app builds and boots without a real
/// Firebase project. With them, `Firebase.initializeApp` succeeds but FCM token
/// retrieval fails (the project does not exist) — push degrades gracefully to a
/// no-op (see `FcmPushTokenSource`). Replace with the real options generated by
/// `flutterfire configure` (or drop in `google-services.json` /
/// `GoogleService-Info.plist`) to enable real delivery.
class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyPLACEHOLDER-ANDROID-0000000000000000',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'amap-en-ligne-placeholder',
    storageBucket: 'amap-en-ligne-placeholder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyPLACEHOLDER-IOS-00000000000000000000',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'amap-en-ligne-placeholder',
    storageBucket: 'amap-en-ligne-placeholder.appspot.com',
    iosBundleId: 'fr.amapenligne.amapEnLigne',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyPLACEHOLDER-WEB-00000000000000000000',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'amap-en-ligne-placeholder',
    authDomain: 'amap-en-ligne-placeholder.firebaseapp.com',
    storageBucket: 'amap-en-ligne-placeholder.appspot.com',
  );
}
